services:
  - type: web
    name: voice-bot
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PREFERRED_OPENAI_MODEL
        value: gpt-3.5-turbo
      - key: PREFERRED_GEMINI_MODEL
        value: gemini-2.0-flash
      - key: USE_MOCK_RESPONSES
        value: false
      - key: USE_ENCRYPTED_KEYS
        value: false
